### ISSUE TITLE
Can't compile with Go 1.22rc1: `undefined: goready`, ...

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/gvisor-tap-vsock#310]
The latest release v0.7.1 and the current main (3cb88d908a919f8aab18c1f017feff4596b996f0) cannot be compiled with Go 1.22rc1 

```console
$ go build ./...
# gvisor.dev/gvisor/pkg/sync
vendor/gvisor.dev/gvisor/pkg/sync/gate_unsafe.go:114:3: undefined: goready
vendor/gvisor.dev/gvisor/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
vendor/gvisor.dev/gvisor/pkg/sync/seqcount.go:87:6: undefined: canSpin
vendor/gvisor.dev/gvisor/pkg/sync/seqcount.go:89:4: undefined: doSpin
```
