### PR TITLE
go.mod: gvisor.dev/gvisor v0.0.0-20231023213702-2691a8f9b1cf  (Support Go1.22)

### LINKED ISSUE #310: Can't compile with Go 1.22rc1: `undefined: goready`, ...
The latest release v0.7.1 and the current main (3cb88d908a919f8aab18c1f017feff4596b996f0) cannot be compiled with Go 1.22rc1 

```console
$ go build ./...
# gvisor.dev/gvisor/pkg/sync
vendor/gvisor.dev/gvisor/pkg/sync/gate_unsafe.go:114:3: undefined: goready
vendor/gvisor.dev/gvisor/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
vendor/gvisor.dev/gvisor/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
vendor/gvisor.dev/gvisor/pkg/sync/seqcount.go:87:6: undefined: canSpin
vendor/gvisor.dev/gvisor/pkg/sync/seqcount.go:89:4: undefined: doSpin
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
This revision is compatible with Go 1.20, 1.21, and 1.22rc1.
v0.0.0-20231024051821-3b00acd67af2 is no longer compatible with Go 1.20.

Fixes #310

### CODE REVIEW

**Comment by cfergeau** [comment]
> This revision is compatible with Go 1.20, 1.21, and 1.22rc1.
> New versions (>= v0.0.0-20231024051821-3b00acd67af2) are no longer compatible with Go 1.20.

Thanks for the tests with multiple go versions! I hope 1.22 final version will also work with this gvisor version to avoid the situation we were in for the 1.21 release

**Review by cfergeau — APPROVED** [review]
